### ISSUE TITLE
OpenWeatherMap[API]の取得

### ISSUE THREAD

**Issue by rik-ing** [rik-ing/ClothesAplication#1]
# やりたいこと
11月18日までにOpenWeatherMap[API]を取得し、天候を表示したい！

**Comment by y-zumi** [comment]
Androideの仕様で，メインスレッドではネットワーク通信ができないので，非同期でAPIに接続する必要がある．

**Comment by y-zumi** [comment]
[正しいAsyncTaskLoaderの使い方](https://qiita.com/akkuma/items/a1252498e95c1f68316c)
[AsyncTaskLoaderの使い方 :Android](http://office2016-01.xyz/asynctaskloader)
ここら辺を参考にして実装中です

**Comment by y-zumi** [comment]
#3 天気情報を取得したので閉じます

**Comment by rik-ing** [comment]
了解です〜！！
